-- Site Nine Project Management Database Schema
-- Created: 2026-01-30
-- Redesigned: 2026-03-03 (Daemon/Possession model — EPC-H-0008)
--
-- This database manages:
-- 1. Daemons  - Named persistent entities, role-bound, Christian-tradition name pool
-- 2. Possessions - Per-session occupancy records (a daemon possesses an agent session)
-- 3. Tasks    - Development work tracking
-- 4. Epics    - Task grouping and organization
-- 5. Messaging - Daemon-to-daemon communication

-- ============================================================================
-- DAEMONS TABLE
-- ============================================================================
-- Stores daemon entities, each bound to a role.
-- Names drawn from Christian-tradition demonology; new names generated by LLM
-- when the pool is exhausted (no daemon unused in last 3 days).
CREATE TABLE IF NOT EXISTS daemons (
    name TEXT PRIMARY KEY,                -- Daemon name (Title Case, e.g., 'Mephistopheles')
    role TEXT NOT NULL                    -- Role this daemon is bound to
        CHECK(role IN ('Administrator', 'Architect', 'Engineer', 'Tester', 'Documentarian', 'Designer', 'Inspector', 'Operator', 'Historian')),
    daemonology TEXT,                     -- Whimsical but thematic first-person bio (3-5 sentences, generated lazily)
    personality TEXT,                     -- Terse trait string (e.g., 'methodical, blunt, suspicious of shortcuts')
    incarnations INTEGER NOT NULL DEFAULT 0, -- Total times this daemon has been summoned (used for roman numeral label)
    last_possession TEXT,                 -- ISO 8601 timestamp of last possession start
    created_at TEXT NOT NULL DEFAULT (datetime('now')),

    CHECK(length(name) > 0)
);

CREATE INDEX IF NOT EXISTS idx_daemons_role ON daemons(role);
CREATE INDEX IF NOT EXISTS idx_daemons_incarnations ON daemons(incarnations);
CREATE INDEX IF NOT EXISTS idx_daemons_last_possession ON daemons(last_possession);

-- ============================================================================
-- POSSESSIONS TABLE
-- ============================================================================
-- Tracks possessions (a daemon occupying an agent session).
-- One possession per OpenCode session. Status lifecycle:
--   ROLE_PENDING -> DAEMON_PENDING -> ACTIVE -> SUSPENDED -> ACTIVE -> EXORCISED
--   or ACTIVE -> EXORCISED (fast path)
CREATE TABLE IF NOT EXISTS possessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    daemon_name TEXT,                     -- Daemon name; NULL during ROLE_PENDING/DAEMON_PENDING
    role TEXT                             -- Role for this possession; NULL during ROLE_PENDING
        CHECK(role IS NULL OR role IN ('Administrator', 'Architect', 'Engineer', 'Tester', 'Documentarian', 'Designer', 'Inspector', 'Operator', 'Historian')),
    possession_log TEXT,                  -- Path to possession log file (includes daemon name + incarnation)

    -- Timing
    start_time TEXT,                      -- ISO 8601 start time; NULL until daemon is bound
    end_time TEXT,                        -- ISO 8601 end time; NULL while active

    -- OpenCode integration
    opencode_session_id TEXT,             -- OpenCode session ID (binds possession to session)
    mode TEXT DEFAULT 'interactive'       -- 'interactive' (Admin/Director) or 'minion' (background worker)
        CHECK(mode IN ('interactive', 'minion')),
    minion_mode_active INTEGER DEFAULT 0,   -- Whether minion mode loop is actively running (0 or 1)

    -- Status
    status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK(status IN ('ACTIVE', 'SUSPENDED', 'EXORCISED', 'ROLE_PENDING', 'DAEMON_PENDING')),

    -- Worker PID (set by minion_worker.py; used by Inquisitor for crash detection)
    worker_pid INTEGER,                   -- OS PID of minion_worker.py process; NULL for interactive, cleared on clean shutdown

    -- Heartbeat (plugin-managed; Inquisitor uses this for rogue detection)
    last_heartbeat_at TEXT,               -- ISO 8601 last heartbeat; Inquisitor exorcises if stale > 3h

    -- Suspension
    suspension_time TEXT,                 -- When possession was suspended (ISO 8601)
    suspension_reason TEXT,               -- Why possession was suspended

    -- Epic context (optional)
    epic_id TEXT,

    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),

    -- Constraints
    CHECK(daemon_name IS NULL OR length(daemon_name) > 0),
    CHECK(possession_log IS NULL OR length(possession_log) > 0),

    -- Foreign keys
    FOREIGN KEY (daemon_name) REFERENCES daemons(name) ON DELETE RESTRICT,
    FOREIGN KEY (epic_id) REFERENCES epics(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_possessions_daemon_name ON possessions(daemon_name);
CREATE INDEX IF NOT EXISTS idx_possessions_role ON possessions(role);
CREATE INDEX IF NOT EXISTS idx_possessions_status ON possessions(status);
CREATE INDEX IF NOT EXISTS idx_possessions_epic_id ON possessions(epic_id);
CREATE INDEX IF NOT EXISTS idx_possessions_mode ON possessions(mode);
CREATE INDEX IF NOT EXISTS idx_possessions_minion_mode ON possessions(minion_mode_active);
CREATE INDEX IF NOT EXISTS idx_possessions_heartbeat ON possessions(last_heartbeat_at);
CREATE INDEX IF NOT EXISTS idx_possessions_suspended ON possessions(status, suspension_time) WHERE status = 'SUSPENDED';
CREATE UNIQUE INDEX IF NOT EXISTS idx_possessions_session_id ON possessions(opencode_session_id) WHERE opencode_session_id IS NOT NULL;

-- Trigger to update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS update_possessions_timestamp
AFTER UPDATE ON possessions
FOR EACH ROW
BEGIN
    UPDATE possessions SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ============================================================================
-- EPICS TABLE
-- ============================================================================
-- Epics are organizational containers for grouping related tasks
CREATE TABLE IF NOT EXISTS epics (
    id TEXT PRIMARY KEY,              -- EPC-[P]-[NNNN] format (e.g., EPC-H-0001)
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'TODO' -- Computed from subtasks via triggers
        CHECK(status IN ('TODO', 'UNDERWAY', 'COMPLETE', 'ABORTED')),
    priority TEXT NOT NULL
        CHECK(priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    aborted_reason TEXT,              -- Only if manually aborted
    locked INTEGER NOT NULL DEFAULT 0, -- 1 if epic is locked (Director-only to set)
    locked_at TEXT,                   -- ISO 8601 timestamp when epic was locked
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    completed_at TEXT,                -- Auto-set when all tasks complete
    aborted_at TEXT,                  -- Set when manually aborted
    file_path TEXT NOT NULL           -- .opencode/work/epics/EPC-H-0001.md
);

CREATE INDEX IF NOT EXISTS idx_epics_status ON epics(status);
CREATE INDEX IF NOT EXISTS idx_epics_priority ON epics(priority);
CREATE INDEX IF NOT EXISTS idx_epics_created ON epics(created_at);

-- Trigger to update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS update_epics_timestamp
AFTER UPDATE ON epics
FOR EACH ROW
BEGIN
    UPDATE epics SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ============================================================================
-- REVIEWS TABLE
-- ============================================================================
-- Tracks review requests for tasks, designs, code, and other artifacts
CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL
        CHECK(type IN ('code', 'task_completion', 'design', 'general')),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'approved', 'rejected')),
    task_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    requested_by TEXT,                -- Daemon name who requested review
    requested_at TEXT NOT NULL DEFAULT (datetime('now')),
    reviewed_by TEXT,                 -- Who completed the review (e.g., 'Director')
    reviewed_at TEXT,
    outcome_reason TEXT,
    artifact_path TEXT,               -- Path to artifact being reviewed

    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_status ON reviews(status);
CREATE INDEX IF NOT EXISTS idx_reviews_type ON reviews(type);
CREATE INDEX IF NOT EXISTS idx_reviews_task_id ON reviews(task_id);
CREATE INDEX IF NOT EXISTS idx_reviews_requested_at ON reviews(requested_at);

-- ============================================================================
-- HANDOFFS TABLE
-- ============================================================================
-- DEPRECATED: Handoffs removed in ADR-014. Table kept for data preservation.
-- Will be dropped in future migration. Use messaging system instead.
CREATE TABLE IF NOT EXISTS handoffs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT NOT NULL,
    from_possession_id INTEGER NOT NULL,  -- Possession handing off the work
    to_role TEXT NOT NULL
        CHECK(to_role IN ('Administrator', 'Architect', 'Engineer', 'Tester', 'Documentarian', 'Designer', 'Inspector', 'Operator', 'Historian')),

    summary TEXT NOT NULL,
    files TEXT,                           -- JSON array of relevant file paths
    acceptance_criteria TEXT,
    notes TEXT,

    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    deleted_at TEXT,                      -- Soft delete timestamp (NULL if active)

    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (from_possession_id) REFERENCES possessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_handoffs_task_id ON handoffs(task_id);
CREATE INDEX IF NOT EXISTS idx_handoffs_from_possession ON handoffs(from_possession_id);
CREATE INDEX IF NOT EXISTS idx_handoffs_to_role ON handoffs(to_role);
CREATE INDEX IF NOT EXISTS idx_handoffs_deleted ON handoffs(deleted_at);

-- ============================================================================
-- TASKS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,                  -- e.g., 'OPR-H-0001', 'ENG-H-0003'
    title TEXT NOT NULL,
    status TEXT NOT NULL
        CHECK(status IN ('TODO', 'UNDERWAY', 'BLOCKED', 'PAUSED', 'REVIEW', 'COMPLETE', 'ABORTED')),
    priority TEXT NOT NULL
        CHECK(priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    role TEXT NOT NULL
        CHECK(role IN ('Administrator', 'Architect', 'Engineer', 'Tester', 'Documentarian', 'Designer', 'Inspector', 'Operator', 'Historian')),
    category TEXT
        CHECK(category IN ('feature', 'bug-fix', 'refactor', 'documentation', 'testing', 'infrastructure', 'security', 'performance', 'architecture', 'maintenance') OR category IS NULL),

    -- Possession tracking
    current_possession_id INTEGER,        -- Possession currently working on this task (or NULL)
    claimed_at TEXT,                      -- ISO 8601 timestamp when task was claimed
    closed_at TEXT,                       -- ISO 8601 timestamp when task was closed
    paused_at TEXT,                       -- ISO 8601 timestamp when work was paused

    -- Time tracking
    actual_hours REAL,

    -- Content
    description TEXT,
    notes TEXT,

    -- Epic relationship
    epic_id TEXT,

    -- Review blocking
    blocks_on_review_id INTEGER,

    -- Metadata
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),

    -- File path
    file_path TEXT NOT NULL,

    -- Constraints
    CHECK(claimed_at IS NULL OR status NOT IN ('TODO')),
    CHECK(closed_at IS NULL OR status IN ('COMPLETE', 'ABORTED', 'PAUSED')),
    CHECK(paused_at IS NULL OR status = 'PAUSED'),

    FOREIGN KEY (current_possession_id) REFERENCES possessions(id) ON DELETE SET NULL,
    FOREIGN KEY (epic_id) REFERENCES epics(id) ON DELETE RESTRICT,
    FOREIGN KEY (blocks_on_review_id) REFERENCES reviews(id) ON DELETE SET NULL
);

-- Task dependencies
CREATE TABLE IF NOT EXISTS task_dependencies (
    task_id TEXT NOT NULL,
    depends_on_task_id TEXT NOT NULL,
    PRIMARY KEY (task_id, depends_on_task_id),
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (depends_on_task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

-- Task blocks
CREATE TABLE IF NOT EXISTS blocks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT NOT NULL,
    block_type TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    resolved_at TEXT,

    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_blocks_task_id ON blocks(task_id);
CREATE INDEX IF NOT EXISTS idx_blocks_resolved ON blocks(resolved_at);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);
CREATE INDEX IF NOT EXISTS idx_tasks_role ON tasks(role);
CREATE INDEX IF NOT EXISTS idx_tasks_current_possession ON tasks(current_possession_id);
CREATE INDEX IF NOT EXISTS idx_tasks_epic_id ON tasks(epic_id);
CREATE INDEX IF NOT EXISTS idx_tasks_blocks_on_review ON tasks(blocks_on_review_id);
CREATE INDEX IF NOT EXISTS idx_tasks_updated ON tasks(updated_at);
CREATE INDEX IF NOT EXISTS idx_tasks_created ON tasks(created_at);

-- Trigger to automatically update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS update_tasks_timestamp
AFTER UPDATE ON tasks
FOR EACH ROW
BEGIN
    UPDATE tasks SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- Trigger to update epic status when task status changes
CREATE TRIGGER IF NOT EXISTS update_epic_status_on_task_change
AFTER UPDATE OF status ON tasks
WHEN NEW.epic_id IS NOT NULL
BEGIN
    UPDATE epics SET
        status = (
            CASE
                WHEN NOT EXISTS (
                    SELECT 1 FROM tasks
                    WHERE epic_id = NEW.epic_id AND status != 'COMPLETE'
                ) THEN 'COMPLETE'
                WHEN EXISTS (
                    SELECT 1 FROM tasks
                    WHERE epic_id = NEW.epic_id
                    AND status IN ('UNDERWAY', 'BLOCKED', 'REVIEW', 'PAUSED')
                ) THEN 'UNDERWAY'
                ELSE 'TODO'
            END
        ),
        completed_at = (
            CASE
                WHEN NOT EXISTS (
                    SELECT 1 FROM tasks
                    WHERE epic_id = NEW.epic_id AND status != 'COMPLETE'
                ) THEN datetime('now')
                ELSE NULL
            END
        ),
        updated_at = datetime('now')
    WHERE id = NEW.epic_id AND status != 'ABORTED';
END;

-- Trigger to update epic status when task is inserted
CREATE TRIGGER IF NOT EXISTS update_epic_status_on_task_insert
AFTER INSERT ON tasks
WHEN NEW.epic_id IS NOT NULL
BEGIN
    UPDATE epics SET
        status = (
            CASE
                WHEN NOT EXISTS (
                    SELECT 1 FROM tasks
                    WHERE epic_id = NEW.epic_id AND status != 'COMPLETE'
                ) THEN 'COMPLETE'
                WHEN EXISTS (
                    SELECT 1 FROM tasks
                    WHERE epic_id = NEW.epic_id
                    AND status IN ('UNDERWAY', 'BLOCKED', 'REVIEW', 'PAUSED')
                ) THEN 'UNDERWAY'
                ELSE 'TODO'
            END
        ),
        updated_at = datetime('now')
    WHERE id = NEW.epic_id AND status != 'ABORTED';
END;

-- ============================================================================
-- TASK TEMPLATES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS task_templates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    title_template TEXT NOT NULL,
    priority TEXT NOT NULL
        CHECK(priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    role TEXT NOT NULL
        CHECK(role IN ('Administrator', 'Architect', 'Engineer', 'Tester', 'Documentarian', 'Designer', 'Inspector', 'Operator', 'Historian')),
    category TEXT,
    objective_template TEXT NOT NULL,
    description_template TEXT,
    variables TEXT,                   -- JSON array of variable names
    usage_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),

    CHECK(length(id) > 0),
    CHECK(length(name) > 0),
    CHECK(length(title_template) > 0),
    CHECK(length(objective_template) > 0)
);

CREATE INDEX IF NOT EXISTS idx_task_templates_role ON task_templates(role);
CREATE INDEX IF NOT EXISTS idx_task_templates_priority ON task_templates(priority);
CREATE INDEX IF NOT EXISTS idx_task_templates_usage ON task_templates(usage_count);

CREATE TRIGGER IF NOT EXISTS update_task_templates_timestamp
AFTER UPDATE ON task_templates
FOR EACH ROW
BEGIN
    UPDATE task_templates SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ============================================================================
-- ARCHITECTURE DOCUMENTS (ADRs) TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS architecture_docs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL
        CHECK(status IN ('PROPOSED', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', 'DEPRECATED')),
    file_path TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_architecture_docs_status ON architecture_docs(status);
CREATE INDEX IF NOT EXISTS idx_architecture_docs_created ON architecture_docs(created_at);

CREATE TRIGGER IF NOT EXISTS update_architecture_docs_timestamp
AFTER UPDATE ON architecture_docs
FOR EACH ROW
BEGIN
    UPDATE architecture_docs SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ============================================================================
-- EPIC-ADR LINKING TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS epic_architecture_docs (
    epic_id TEXT NOT NULL,
    adr_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (epic_id, adr_id),
    FOREIGN KEY (epic_id) REFERENCES epics(id) ON DELETE CASCADE,
    FOREIGN KEY (adr_id) REFERENCES architecture_docs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_epic_architecture_docs_epic ON epic_architecture_docs(epic_id);
CREATE INDEX IF NOT EXISTS idx_epic_architecture_docs_adr ON epic_architecture_docs(adr_id);

-- ============================================================================
-- TASK-ADR LINKING TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS task_architecture_docs (
    task_id TEXT NOT NULL,
    adr_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (task_id, adr_id),
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (adr_id) REFERENCES architecture_docs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_task_architecture_docs_task ON task_architecture_docs(task_id);
CREATE INDEX IF NOT EXISTS idx_task_architecture_docs_adr ON task_architecture_docs(adr_id);

-- ============================================================================
-- MESSAGING TABLES
-- ============================================================================

-- Conversations and discussions
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,              -- CONV-[NNNN] format
    subject TEXT NOT NULL,
    type TEXT NOT NULL
        CHECK(type IN ('conversation', 'discussion')),
    status TEXT NOT NULL DEFAULT 'open'
        CHECK(status IN ('open', 'closed')),

    -- Participants (for type='conversation')
    participant_1_id INTEGER,         -- First participant possession ID
    participant_2_id INTEGER,         -- Second participant possession ID

    -- Scope (for type='discussion')
    scope_type TEXT
        CHECK(scope_type IN ('role', 'epic', 'all') OR scope_type IS NULL),
    scope_role TEXT,
    scope_epic_id TEXT,

    -- Optional context links
    task_id TEXT,
    epic_id TEXT,

    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    closed_at TEXT,

    FOREIGN KEY (participant_1_id) REFERENCES possessions(id),
    FOREIGN KEY (participant_2_id) REFERENCES possessions(id),
    FOREIGN KEY (scope_epic_id) REFERENCES epics(id),
    FOREIGN KEY (task_id) REFERENCES tasks(id),
    FOREIGN KEY (epic_id) REFERENCES epics(id)
);

CREATE INDEX IF NOT EXISTS idx_conversations_type ON conversations(type);
CREATE INDEX IF NOT EXISTS idx_conversations_status ON conversations(status);
CREATE INDEX IF NOT EXISTS idx_conversations_participant_1 ON conversations(participant_1_id);
CREATE INDEX IF NOT EXISTS idx_conversations_participant_2 ON conversations(participant_2_id);
CREATE INDEX IF NOT EXISTS idx_conversations_updated ON conversations(updated_at);

CREATE TRIGGER IF NOT EXISTS update_conversations_timestamp
AFTER UPDATE ON conversations
FOR EACH ROW
BEGIN
    UPDATE conversations SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- Messages within conversations or discussions
CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,              -- MSG-[P]-[NNNN] format
    conversation_id TEXT NOT NULL,
    from_possession_id INTEGER NOT NULL, -- Sender possession ID
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'MEDIUM'
        CHECK(priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),

    -- Threading (discussions only)
    parent_message_id TEXT,
    thread_root_id TEXT,

    -- Optional context links
    task_id TEXT,
    epic_id TEXT,
    artifact_path TEXT,

    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT,

    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (from_possession_id) REFERENCES possessions(id),
    FOREIGN KEY (parent_message_id) REFERENCES messages(id),
    FOREIGN KEY (thread_root_id) REFERENCES messages(id),
    FOREIGN KEY (task_id) REFERENCES tasks(id),
    FOREIGN KEY (epic_id) REFERENCES epics(id)
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_from_possession ON messages(from_possession_id);
CREATE INDEX IF NOT EXISTS idx_messages_priority ON messages(priority);
CREATE INDEX IF NOT EXISTS idx_messages_created ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_messages_thread_root ON messages(thread_root_id);

CREATE TRIGGER IF NOT EXISTS update_conversation_on_message_insert
AFTER INSERT ON messages
FOR EACH ROW
BEGIN
    UPDATE conversations SET updated_at = datetime('now') WHERE id = NEW.conversation_id;
END;

-- Tracks when each possession last viewed a conversation (for unread detection)
CREATE TABLE IF NOT EXISTS conversation_views (
    conversation_id TEXT NOT NULL,
    possession_id INTEGER NOT NULL,
    last_viewed_at TEXT NOT NULL DEFAULT (datetime('now')),

    PRIMARY KEY (conversation_id, possession_id),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (possession_id) REFERENCES possessions(id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_views_possession ON conversation_views(possession_id);

-- Tracks when each possession acknowledges/processes a specific message
CREATE TABLE IF NOT EXISTS message_acknowledgements (
    message_id TEXT NOT NULL,
    possession_id INTEGER NOT NULL,
    acknowledged_at TEXT NOT NULL DEFAULT (datetime('now')),

    PRIMARY KEY (message_id, possession_id),
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
    FOREIGN KEY (possession_id) REFERENCES possessions(id)
);

CREATE INDEX IF NOT EXISTS idx_message_acks_message ON message_acknowledgements(message_id);
CREATE INDEX IF NOT EXISTS idx_message_acks_possession ON message_acknowledgements(possession_id);

-- Status queue for minion-to-director toast notifications.
-- Minions push short status messages here; the OpenCode plugin pops and toasts
-- them in the interactive session. Cleared on s9 summon.
CREATE TABLE IF NOT EXISTS status_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    possession_id INTEGER NOT NULL,
    message TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (possession_id) REFERENCES possessions(id)
);

CREATE INDEX IF NOT EXISTS idx_status_queue_created ON status_queue(created_at);

-- ============================================================================
-- TASK STATUS VIEW
-- ============================================================================
CREATE VIEW IF NOT EXISTS task_status_view AS
    SELECT
        t.id,
        t.status as work_status,
        CASE
            -- Terminal states pass through
            WHEN t.status IN ('COMPLETE', 'ABORTED') THEN t.status

            -- Check for external blocker
            WHEN EXISTS (
                SELECT 1 FROM blocks b
                WHERE b.task_id = t.id AND b.resolved_at IS NULL
                AND b.block_type != 'review' AND b.block_type != 'dependency'
            ) THEN 'BLOCKED_EXTERNAL'

            -- Check for review blocker
            WHEN EXISTS (
                SELECT 1 FROM blocks b
                WHERE b.task_id = t.id AND b.resolved_at IS NULL
                AND b.block_type = 'review'
            ) THEN 'BLOCKED_REVIEW'

            -- Check for dependency blocker
            WHEN EXISTS (
                SELECT 1 FROM task_dependencies td
                INNER JOIN tasks dep ON td.depends_on_task_id = dep.id
                WHERE td.task_id = t.id AND dep.status != 'COMPLETE'
            ) THEN 'BLOCKED_DEPENDENCY'

            -- No blockers, pass through work status
            ELSE t.status
        END as effective_status
    FROM tasks t;

-- ============================================================================
-- DAEMON SEED DATA
-- ============================================================================
-- Minimal canonical seed: one daemon per role, drawn from the Ars Goetia
-- and Pseudomonarchia Daemonum tradition.
-- daemonology and personality are NULL on creation; generated by LLM on first summon.
-- When all daemons for a role have been used within 3 days, summon_daemon()
-- returns None and the caller must invent a new daemon name.

INSERT OR IGNORE INTO daemons (name, role) VALUES
    ('mephistopheles', 'Administrator'),
    ('mulciber',       'Architect'),
    ('azazel',         'Engineer'),
    ('lilith',         'Tester'),
    ('decarabia',      'Documentarian'),
    ('sitri',          'Designer'),
    ('andromalius',    'Inspector'),
    ('dagon',          'Operator'),
    ('stolas',         'Historian');
